- name: Sync latest website content
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    key: ${{ secrets.KEY }}
    port: ${{ secrets.PORT }}
    script: cd brighton && git pull https://github.com/Depart-de-Sentier/brightcon.git
